import {
  idCardPattern,
  nameEnPattern,
  nameThPattern,
  passportPattern,
  phonePattern,
} from './form-validators';

export function createDefaultUserForm(FormBuilder: any, Validators: any) {
  return FormBuilder.group({
    id: [],
    idCardNo: [null, [Validators.required, Validators.pattern(idCardPattern)]],
    passportNo: [null, [Validators.pattern(passportPattern)]],
    passportStartDate: [],
    passportEndDate: [],
    prefixTh: [null, Validators.required],
    firstNameTh: [
      null,
      [Validators.required, Validators.pattern(nameThPattern)],
    ],
    middleNameTh: [],
    lastNameTh: [
      null,
      [Validators.required, Validators.pattern(nameThPattern)],
    ],
    prefixEn: [null, Validators.required],
    firstNameEn: [
      null,
      [Validators.required, Validators.pattern(nameEnPattern)],
    ],
    middleNameEn: [null],
    lastNameEn: [
      null,
      [Validators.required, Validators.pattern(nameEnPattern)],
    ],
    sex: [null, Validators.required],
    birthDate: [null, Validators.required],
    email: [null, [Validators.required, Validators.email]],
    contactPhone: [
      null,
      [Validators.required, Validators.pattern(phonePattern)],
    ],
    workPhone: [null, [Validators.required, Validators.pattern(phonePattern)]],
    nationality: ['TH'],
    country: [],
    visatype: [],
    visaclass: [],
    visaenddate: [],
  });
}
export function createDefaultRequestForm(FormBuilder: any) {
  return FormBuilder.group({
    currentprocess: null,
    requeststatus: null,
    updatedate: null,
    licenseid: null,
    staffid: null,
    systemtype: null,
    requesttype: null,
    requesteduocupy: null,
    requestfor: null,
    schoolid: null,
    idcardno: null,
    passportno: null,
    passportstartdate: null,
    passportenddate: null,
    prefixth: null,
    firstnameth: null,
    lastnameth: null,
    prefixen: null,
    firstnameen: null,
    lastnameen: null,
    sex: null,
    birthdate: null,
    email: null,
    position: null,
    educationoccupy: null,
    contactphone: null,
    workphone: null,
    nationality: null,
    country: null,
    coordinatorinfo: null,
    visainfo: null,
    userpermission: null,
    addressinfo: null,
    schooladdrinfo: null,
    eduinfo: null,
    teachinginfo: null,
    reasoninfo: null,
    fileinfo: null,
    otherreason: null,
    refperson: null,
    prohibitproperty: null,
    checkprohibitproperty: null,
    checksubresult: null,
    checkfinalresult: null,
    checkhistory: null,
    approveresult: null,
    paymentstatus: null,
    ref1: null,
    ref2: null,
    ref3: null,
  });
}
