export type FormMode = 'view' | 'edit';

export class SchoolRequest {
  ref1 = null;
  ref2 = null;
  ref3 = null;

  addressinfo = null;
  approveresult = null;
  birthdate = null;
  checkfinalresult = null;
  checkhistory = null;
  checkprohibitproperty = null;
  checksubresult = null;
  competencyinfo = null;
  contactphone = null;
  coordinatorinfo = null;
  country = null;
  currentprocess = null;
  educationoccupy = null;
  eduinfo = null;
  email = null;
  experienceinfo = null;
  feerefundinfo = null;
  fileinfo = null;
  firstnameen = null;
  firstnameth = null;
  grantionteachinglicenseinfo = null;
  hiringinfo = null;
  // id: string // only when update
  idcardno = null;
  imagefileid = null;
  lastnameen = null;
  lastnameth = null;
  licenseid = null;
  middlenameen = null;
  middlenameth = null;
  nationality = null;
  otherreason = null;
  passportenddate = null;
  passportno = null;
  passportstartdate = null;
  paymentstatus = null;
  performanceinfo = null;
  position = null;
  prefixen = null;
  prefixth = null;
  prohibitproperty = null;
  reasoninfo = null;
  refperson = null;
  replacereasoninfo = null;
  requestdate = null;
  requesteduocupy = null;
  requestfor = null;
  requestno = null;
  requeststatus = null;
  requesttype = null;
  rewardtype = null;
  schooladdrinfo = null;
  schoolid = null;
  sex = null;
  staffid = null;
  submissiondocdate = null;
  submissiondocno = null;
  subtype = null;
  systemtype = null;
  teachinginfo = null;
  testresultcompareinfo = null;
  transferknowledgeinfo = null;
  uniquetimestamp = null;
  updatedate = null;
  userpermission = null;
  visainfo = null;
  workphone = null;

  osoiinfo = null; // ข้อมูลใบคำขอ OSOI
  osoimember = null; // คณะผู้ร่วมพัฒนา
  osoicheck = null; // ยืนยันผลการตวจสอบ
  osoiresult = null; // ผลการพิจารณาคณะกรรมการ
  osoireject = null; // คัดค้าน
  osoiwithdraw = null; // เพิกถอน
}
